### ISSUE TITLE
How to use the package?

### ISSUE THREAD

**Issue by ghost** [stepelu/lua-rclient#1]
Hi, I download this package and placed the files in my working directory. 

Started, the R client using 

`library("Rserve")`
`Rserve(args="--no-save")`

I copied your example and tried to run it using Luajit, but I get the following error message,

luajit: error loading module 'rclient' from file './rclient.lua':
    ./rclient.lua:17: '=' expected near 'local'
stack traceback:
    [C]: at 0x00474980
    [C]: in function 'require'
    test_rclient.lua:1: in main chunk
    [C]: at 0x004061d0

**Comment by stepelu** [comment]
Hi, the rclient module does not include any `rclient.lua` file (the closest would be `rclient/_rclient.lua`) so I assume it's a script you have written yourself. 

My guess is that you put such `rclient.lua` next to the LuaJIT executable and hence `require()` would try to load it instead of `rclient/init.lua` (because the former has higher priority in `package.path`). 
Please check what is present on line 17 of the `rclient.lua` file, and in any case move it out of the way so that it does not interfere with the rclient module.
